# Generated by Django 4.2.5 on 2023-09-28 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoninfo',
            name='last_view_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 23, 6, 39, 787482)),
        ),
    ]
